(WIP) LKE-2827 return failed rows
Linkurious/lke-plugin-csv-importer pull request #5
Opened 2021-06-07 14:13 UTC by renato-rg

Jira: https://linkurious.atlassian.net/browse/LKE-2822

2021-06-07 16:22 UTC, aminerhanemi requested changes

2021-06-07 16:22 UTC, aminerhanemi commented on src/backend/routeHandler.ts
> +        failed: failedRows
if we already now the possible errors we can have a Map with the key as the error in the value as an array of rows number

2021-06-07 16:22 UTC, aminerhanemi commented on src/public/cards/entityProperties.ts
> +      console.log({data});
remove

2021-06-10 13:53 UTC, aminerhanemi requested changes

2021-06-10 13:53 UTC, aminerhanemi commented on src/public/cards/entityProperties.ts
> -      headersFinal.forEach((header: string) => {
why removing this part ?

2021-06-10 14:05 UTC, francescoinfante requested changes

2021-06-10 14:24 UTC, renato-rg commented on src/backend/graphItemService.ts
> +            source: await GraphItemService.getNodeID(rc, sourceKey, sourceType, rowValues[0]),
@francescoinfante I check if they are successful inside `getNodeId` otherwise I throw a SOURCE_TARGET_NOT_FOUND. Is that what you meant?

2021-06-10 14:47 UTC, francescoinfante commented on src/backend/graphItemService.ts
> +            source: await GraphItemService.getNodeID(rc, sourceKey, sourceType, rowValues[0]),
indeed, I reviewed too fast :)

2021-06-10 14:53 UTC, aminerhanemi approved these changes

2021-06-10 14:57 UTC, francescoinfante approved these changes

2021-06-10 15:01 UTC, merged

2021-06-11 07:03 UTC, aminerhanemi commented on src/backend/graphItemService.ts
> +      error: errors.toString()
Why returning a string here ? it is better to return an object with key 'type of the error' and value the list of the row